# docker-compose.yml placeholder
version: '3.8'

services:
  plant-app:
    build: .
    container_name: plant_disease_detector
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./models:/app/models
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
